Disable coverage upload step in CI workflow

diff --git a/.github/workflows/_common.yml b/.github/workflows/_common.yml
--- a/.github/workflows/_common.yml
+++ b/.github/workflows/_common.yml
@@ -62,12 +62,12 @@ jobs:
       - name: Run tests
         run: make test
 
-      - name: Upload coverage
-        uses: codecov/codecov-action@v4
-        if: ${{ inputs.os == 'ubuntu-latest' && matrix.python-version == '3.9' && (github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork)) }}
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          fail_ci_if_error: true
+      # - name: Upload coverage
+      #   uses: codecov/codecov-action@v4
+      #   if: ${{ inputs.os == 'ubuntu-latest' && matrix.python-version == '3.9' && (github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork)) }}
+      #   with:
+      #     token: ${{ secrets.CODECOV_TOKEN }}
+      #     fail_ci_if_error: true
 
       - name: Run checks
         run: make check
